In [5]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
arr = np.array(my_list) #casting to numpy array

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11) #creating a numpy array from 0 to 10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2) #returns even numbers

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3) #numpy array of 0's

array([0., 0., 0.])

In [13]:
np.zeros((5,5)) #numpy arrays of 5 col and 5 row

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3)) #numpy array of 1's

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,100) #evenly spaced array with 100 digits

array([0.])

In [18]:
np.eye(3)#creating identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(5)#creating an array of values b/w 0's and 1's (uniform distribution)

array([0.22697452, 0.58187891, 0.16878404, 0.9170911 , 0.27635891])

In [20]:
np.random.rand(5,5) #creates a 5 X5 matrix 

array([[0.91387708, 0.93575066, 0.43280502, 0.87499911, 0.23429357],
       [0.48869866, 0.64308014, 0.18335145, 0.30203165, 0.46545774],
       [0.34160676, 0.60366237, 0.85838134, 0.66878466, 0.53586786],
       [0.95799469, 0.40156057, 0.36903615, 0.38817499, 0.04759607],
       [0.31531723, 0.13444057, 0.94842349, 0.15043656, 0.45876014]])

In [21]:
np.random.randn(2)   #2 gaussian distribution numbers generated

array([-0.23717058, -1.78326039])

In [22]:
np.random.randn(2,2)

array([[-2.95715302, -0.92374245],
       [ 1.34291648,  0.07406471]])

In [26]:
np.random.randint(0,99,(3,3)) #generates a 3 X 3 matrix with integers from 0 to 99

array([[12, 93, 22],
       [78, 29, 88],
       [45, 83, 96]])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([37, 24, 23, 10, 40, 40, 23, 22,  5, 31])

In [31]:
arr.reshape(5,5) #reshapes the array with the dimensions as mentioned

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max() #returns max value of array

40

In [33]:
ranarr.min()#returns  min value of array

5

In [34]:
ranarr.argmax() #returns index location of max value

4

In [35]:
ranarr.argmin() #returns minimum location of min value

8

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
 arr.shape #returns dimensions

(5, 5)

In [39]:
type(arr)

numpy.ndarray

In [40]:
arr.dtype #type of values in array

dtype('int32')